services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/api/src/
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
